name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    if: contains(github.event.head_commit.message, 'deploy')
    
    steps:
    - uses: actions/checkout@v4

    - name: Build and Deploy React app to GitHub Pages
      run: |
        git config --global user.email "caihedoro@gmail.com"
        git config --global user.name "Chukwuemeka Ihedoro"
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm install
        npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
